spring.application.name=venda-service
server.port=8082
# Endereço do servidor Kafka (Bootstrap Server)
spring.kafka.bootstrap-servers=localhost:9092

# Configurações do Produtor (Producer) - Quem envia as mensagens
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer




